/* =====================================================================
   TECHNO · Service worker
   Offline-first: precache the core shell + curriculum, then cache every
   same-origin asset on first fetch. The whole app works with no network
   after the first visit.

   CORE is generated by tools/gen_sw.mjs from index.html — run that tool
   after adding or removing a script/stylesheet rather than editing by hand.
   ===================================================================== */
const CACHE = "techno-managerial-v11";
const CACHE_PREFIX = "techno-managerial-";
const CORE = [
  "./fonts/8vIH7w4qzmVxm25L9G78HEZnMg.woff2",
  "./fonts/8vIH7w4qzmVxm2BL9G78HEY.woff2",
  "./fonts/8vIH7w4qzmVxm2NL9G78HEZnMg.woff2",
  "./fonts/ieVn2YZDLWuGJpnzaiwFXS9tYtpQ59CxCis4UvI.woff2",
  "./fonts/ieVn2YZDLWuGJpnzaiwFXS9tYtpS59CxCis4UvI.woff2",
  "./fonts/ieVn2YZDLWuGJpnzaiwFXS9tYtpT59CxCis4UvI.woff2",
  "./fonts/ieVn2YZDLWuGJpnzaiwFXS9tYtpd59CxCis4.woff2",
  "./fonts/ieVo2YZDLWuGJpnzaiwFXS9tYtpY_d6T_POl0fRJeyWyosBA5XxjLdSL17o24Q.woff2",
  "./fonts/ieVo2YZDLWuGJpnzaiwFXS9tYtpY_d6T_POl0fRJeyWyosBB5XxjLdSL17o24Q.woff2",
  "./fonts/ieVo2YZDLWuGJpnzaiwFXS9tYtpY_d6T_POl0fRJeyWyosBD5XxjLdSL17o24Q.woff2",
  "./fonts/ieVo2YZDLWuGJpnzaiwFXS9tYtpY_d6T_POl0fRJeyWyosBO5XxjLdSL17o.woff2",
  "./fonts/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPx3cwgknk-6nFg.woff2",
  "./fonts/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPx7cwgknk-6nFg.woff2",
  "./fonts/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxDcwgknk-4.woff2",
  "./fonts/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxPcwgknk-6nFg.woff2",
  "./fonts/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPxTcwgknk-6nFg.woff2",
  "./fonts/tDbv2o-flEEny0FZhsfKu5WU4zr3E_BX0PnT8RD8yKwBNntkaToggR7BYRbKPx_cwgknk-6nFg.woff2",
  "./",
  "./index.html",
  "./css/styles.css",
  "./css/exam.css",
  "./css/pwa.css",
  "./js/track-hld.js",
  "./js/track-lld.js",
  "./js/track-data.js",
  "./js/practice-content.js",
  "./js/exam.js",
  "./js/pwa.js",
  "./js/app.js",
  "./icon.svg",
  "./manifest.webmanifest"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(CORE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  let url;
  try { url = new URL(req.url); } catch (_) { return; }
  if (url.origin !== self.location.origin) return; // never touch cross-origin

  // Cache-first, with runtime caching for anything not precached.
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => {
        // SPA fallback for navigations when offline and uncached
        if (req.mode === "navigate") return caches.match("./index.html");
        return new Response("", { status: 504, statusText: "offline" });
      });
    })
  );
});
