#!/usr/bin/env python3
"""Wire self-hosted @font-face into one Atlas app (idempotent).

Uses gen_fontface logic to produce correct @font-face rules from the app's
bundled woff2 files, then:
  1. prepends the @font-face block to css/styles.css (once),
  2. inserts the woff2 paths into the sw.js CORE precache array (once),
  3. bumps the sw.js CACHE version by one (only when it actually changes files).

Usage:  PYTHONPATH=tools/pylib python3 tools/apply_fonts.py <app_dir>
"""
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
import gen_fontface as g  # noqa: E402

MARKER = "/* Self-hosted fonts (offline). Generated by tools/gen_fontface.py. */"


def build_faces(app_dir):
    fonts_dir = os.path.join(app_dir, "fonts")
    files = sorted(f for f in os.listdir(fonts_dir) if f.lower().endswith(".woff2"))
    faces, core = [], []
    from fontTools.ttLib import TTFont
    for f in files:
        font = TTFont(os.path.join(fonts_dir, f), lazy=True, fontNumber=0)
        fam = g.family_name(font)
        style = "italic" if g.is_italic(font) else "normal"
        weight = g.weight_decl(font)
        urange = g.to_ranges(g.codepoints(font))
        font.close()
        if not urange:
            continue
        faces.append(
            "@font-face {\n"
            '  font-family: "%s";\n'
            "  font-style: %s;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            '  src: url("../fonts/%s") format("woff2");\n'
            "  unicode-range: %s;\n"
            "}" % (fam, style, weight, f, urange)
        )
        core.append("./fonts/" + f)
    return faces, core


def patch_css(app_dir, faces):
    css_path = os.path.join(app_dir, "css", "styles.css")
    with open(css_path, "r", encoding="utf-8") as fh:
        css = fh.read()
    if MARKER in css:
        return False
    block = MARKER + "\n" + "\n".join(faces) + "\n\n"
    with open(css_path, "w", encoding="utf-8") as fh:
        fh.write(block + css)
    return True


def patch_sw(app_dir, core):
    sw_path = os.path.join(app_dir, "sw.js")
    with open(sw_path, "r", encoding="utf-8") as fh:
        sw = fh.read()
    changed = False
    if "./fonts/" not in sw:
        lines = "".join('  "%s",\n' % p for p in core)
        sw = re.sub(r"(const CORE = \[\n)", r"\1" + lines, sw, count=1)
        changed = True
    if changed:
        def bump(m):
            return '%s%d"' % (m.group(1), int(m.group(2)) + 1)
        sw = re.sub(r'(const CACHE = "[a-z-]+-v)(\d+)"', bump, sw, count=1)
    if changed:
        with open(sw_path, "w", encoding="utf-8") as fh:
            fh.write(sw)
    return changed


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: apply_fonts.py <app_dir>")
    app_dir = os.path.abspath(sys.argv[1])
    faces, core = build_faces(app_dir)
    css_changed = patch_css(app_dir, faces)
    sw_changed = patch_sw(app_dir, core)
    print("%s: faces=%d css_patched=%s sw_patched=%s" % (
        os.path.basename(app_dir), len(faces), css_changed, sw_changed))


if __name__ == "__main__":
    main()
