#!/usr/bin/env python3
"""Generate correct @font-face CSS for a bundled fonts/ directory.

The Atlas apps ship Google-Fonts woff2 subsets with opaque hashed filenames,
so @font-face cannot be authored by guessing from the filename. This script
introspects each woff2 with fontTools to recover the real family name, weight
(or variable weight range), italic flag, and the actual unicode coverage, then
emits one @font-face per file with a precise unicode-range.

Usage:
    python3 tools/gen_fontface.py <app_dir>

Prints (to stdout):
    - a CSS block of @font-face rules (relative url ../fonts/<file>)
    - a JSON list of the woff2 files (relative ./fonts/<file>) for the SW CORE

Read-only: it never writes to the app; the caller wires the output in.
"""
import json
import os
import sys

from fontTools.ttLib import TTFont


def codepoints(font):
    best = font.getBestCmap()
    return sorted(best.keys()) if best else []


def to_ranges(cps):
    """Compress a sorted codepoint list into CSS unicode-range tokens."""
    ranges = []
    start = prev = None
    for cp in cps:
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            ranges.append((start, prev))
            start = prev = cp
    if start is not None:
        ranges.append((start, prev))
    out = []
    for lo, hi in ranges:
        out.append("U+%04X" % lo if lo == hi else "U+%04X-%04X" % (lo, hi))
    return ", ".join(out)


def family_name(font):
    name = font["name"]
    # 16 = typographic family, 1 = legacy family
    for nid in (16, 1):
        rec = name.getDebugName(nid)
        if rec:
            return rec.strip()
    return "Unknown"


def is_italic(font):
    if "OS/2" in font:
        if font["OS/2"].fsSelection & 0x01:
            return True
    if "head" in font and (font["head"].macStyle & 0x02):
        return True
    sub = font["name"].getDebugName(17) or font["name"].getDebugName(2) or ""
    return "italic" in sub.lower()


def weight_decl(font):
    if "fvar" in font:
        for axis in font["fvar"].axes:
            if axis.axisTag == "wght":
                lo, hi = int(round(axis.minValue)), int(round(axis.maxValue))
                return "%d %d" % (lo, hi) if lo != hi else str(lo)
    if "OS/2" in font:
        return str(font["OS/2"].usWeightClass)
    return "400"


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_fontface.py <app_dir>")
    app_dir = os.path.abspath(sys.argv[1])
    fonts_dir = os.path.join(app_dir, "fonts")
    files = sorted(f for f in os.listdir(fonts_dir) if f.lower().endswith(".woff2"))
    faces = []
    core = []
    for f in files:
        path = os.path.join(fonts_dir, f)
        font = TTFont(path, lazy=True, fontNumber=0)
        fam = family_name(font)
        style = "italic" if is_italic(font) else "normal"
        weight = weight_decl(font)
        urange = to_ranges(codepoints(font))
        font.close()
        if not urange:
            continue
        face = (
            "@font-face {\n"
            '  font-family: "%s";\n'
            "  font-style: %s;\n"
            "  font-weight: %s;\n"
            "  font-display: swap;\n"
            '  src: url("../fonts/%s") format("woff2");\n'
            "  unicode-range: %s;\n"
            "}" % (fam, style, weight, f, urange)
        )
        faces.append(face)
        core.append("./fonts/" + f)
    print("/* Self-hosted fonts (offline). Generated by tools/gen_fontface.py. */")
    print("\n".join(faces))
    print("\n/*__CORE__*/")
    print(json.dumps(core, indent=2))


if __name__ == "__main__":
    main()
