#!/usr/bin/env node
/*
 * Regenerate an Atlas app's service worker precache list from what its
 * index.html actually loads.
 *
 *   node tools/gen_sw.mjs <appDir> [--bump]
 *   node tools/gen_sw.mjs --all --bump
 *
 * Cache.addAll is all-or-nothing, so a CORE list that drifts out of sync with
 * index.html silently breaks offline support for the whole app. Generating the
 * list removes that class of bug, and --bump rolls the CACHE version so
 * returning users don't get served a stale shell.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const ALL_APPS = [
  "hld-lld-academy", "dsa-patterns-academy", "cyber-academy",
  "data-eng-academy", "techno-managerial-academy",
  "behavioral-academy", "ml-ai-academy",
];

const SW_TEMPLATE = (label, cache, prefix, core) => `/* =====================================================================
   ${label} · Service worker
   Offline-first: precache the core shell + curriculum, then cache every
   same-origin asset on first fetch. The whole app works with no network
   after the first visit.

   CORE is generated by tools/gen_sw.mjs from index.html — run that tool
   after adding or removing a script/stylesheet rather than editing by hand.
   ===================================================================== */
const CACHE = "${cache}";
const CACHE_PREFIX = "${prefix}";
const CORE = [
${core.map((c) => `  "${c}"`).join(",\n")}
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(CORE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  let url;
  try { url = new URL(req.url); } catch (_) { return; }
  if (url.origin !== self.location.origin) return; // never touch cross-origin

  // Cache-first, with runtime caching for anything not precached.
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => {
        // SPA fallback for navigations when offline and uncached
        if (req.mode === "navigate") return caches.match("./index.html");
        return new Response("", { status: 504, statusText: "offline" });
      });
    })
  );
});
`;

function coreFor(dir) {
  const appDir = join(ROOT, dir);
  const index = readFileSync(join(appDir, "index.html"), "utf8");

  const fontsDir = join(appDir, "fonts");
  const fonts = existsSync(fontsDir)
    ? readdirSync(fontsDir).filter((f) => f.endsWith(".woff2")).sort().map((f) => `./fonts/${f}`)
    : [];

  const css = [...index.matchAll(/<link[^>]+href="([^"]+\.css)"/g)].map((m) => m[1]);
  const js = [...index.matchAll(/<script[^>]+src="([^"]+\.js)"/g)].map((m) => m[1]);
  const norm = (p) => (p.startsWith("./") ? p : "./" + p.replace(/^\/+/, ""));

  const core = [
    ...fonts,
    "./", "./index.html",
    ...css.map(norm),
    ...js.map(norm),
  ];
  if (existsSync(join(appDir, "icon.svg"))) core.push("./icon.svg");
  if (existsSync(join(appDir, "manifest.webmanifest"))) core.push("./manifest.webmanifest");

  // every entry must exist on disk or install() rejects and offline breaks
  const missing = core.filter((c) => {
    const rel = c === "./" ? "index.html" : c.replace(/^\.\//, "");
    return !existsSync(join(appDir, rel));
  });
  if (missing.length) {
    console.error(`ERROR [${dir}] index.html references files that do not exist: ${missing.join(", ")}`);
    process.exitCode = 1;
    return null;
  }
  return core;
}

function run(dir, bump) {
  const swPath = join(ROOT, dir, "sw.js");
  const existing = existsSync(swPath) ? readFileSync(swPath, "utf8") : "";
  const cm = existing.match(/const CACHE\s*=\s*"([^"]+)"/);
  const label = (existing.match(/^\/\*[\s\S]*?\n\s+(\S+) · Service worker/m) || [])[1]
    || basename(dir).split("-")[0].toUpperCase();

  let cache = cm ? cm[1] : `${basename(dir)}-v1`;
  const parts = cache.match(/^(.*-v)(\d+)$/);
  const prefix = parts ? parts[1].replace(/v$/, "") : cache + "-";
  if (bump && parts) cache = parts[1] + (parseInt(parts[2], 10) + 1);

  const core = coreFor(dir);
  if (!core) return;
  writeFileSync(swPath, SW_TEMPLATE(label, cache, prefix, core), "utf8");
  console.log(`ok   ${dir}: CACHE=${cache}, ${core.length} CORE entries`);
}

const args = process.argv.slice(2);
const bump = args.includes("--bump");
const dirs = args.includes("--all") ? ALL_APPS : args.filter((a) => !a.startsWith("--")).map((a) => basename(a.replace(/\/+$/, "")));
if (!dirs.length) { console.error("usage: gen_sw.mjs <appDir>... [--bump] | --all [--bump]"); process.exit(1); }
for (const d of dirs) {
  if (!existsSync(join(ROOT, d, "index.html"))) { console.log(`skip ${d}: no index.html`); continue; }
  run(d, bump);
}
